### ISSUE TITLE
Constant 'Wrong current password' error

### ISSUE THREAD

**Issue by ekaterina-git** [bizley/yii2-podium#64] opened 2016-12-04 12:03 UTC
Hi @bizley ,
could you help me?

I'd recently installed Podium 0.5 with such params (web.php):
`'forum'   => [
            'class'         => \bizley\podium\Podium::class,
            'userComponent' => 'user',
            'adminId'       => 1,
        ],`
Installation was successful, but when I logged into my main application and then came to Podium settings, I kept getting 'Wrong current password'... I'm sorry, I've read all wiki instructions and I simply don't understand what's wrong. I looked into Poidum DB and noticed that the password hash for this user was empty.

**Comment by bizley** [comment] 2016-12-04 12:13
What is the name of the field that keeps hash password for your `user` component underlying model's DB table?

**Comment by bizley** [comment] 2016-12-05 07:18
@Katenkka is it ok now? Password hash is not set in `podium_user` table for inherited account because the other user table is checked for password in that case. That is why Podium needs to get the name of field storing the hash if it's different from `password_hash`.

This mechanism assumes the password has been hashed using the same way as the default Podium identity password so module is able to verify it. This is obvious pitfall but I'm working on a way to tell Podium what to do in case of non-standard password generating.

**Comment by ekaterina-git** [comment] 2016-12-05 07:31
Hi, @bizley . Thanks for your answer. I didn't get the chance to check it yet, but I think I tried using `userPasswordField` option in config... Not sure. Anyway, I'll try it tonight and then tell you if it's okay. Thanks again for help!

**Comment by bizley** [comment] 2016-12-05 07:37
First check if it's needed at all:
- Is there the `password_hash` column in the other user table? You don't have to add `userPasswordField` in this case.
- If there is column there storing password hash with the different name add `userPasswordField` in configuration.

**Comment by ekaterina-git** [comment] 2016-12-07 19:53
My user table has field `password` so I put into config `userPasswordField => 'password'` and reinstalled Podium.
Unfortunately, it didn't help :(

**Comment by bizley** [comment] 2016-12-07 19:57
Please provide me the code used to generate the password stored in the `password` database column.

**Comment by ekaterina-git** [comment] 2016-12-07 20:03
It's not my code, I use 'amnah/yii2-user' as user component.

**Comment by bizley** [comment] 2016-12-07 20:17
I went through the code of this extension and it looks like it should work with your configuration, weird...
Let me install this on my local env and I will get back to you.

**Comment by bizley** [comment] 2016-12-07 20:40
Just one more question - is that account created using email/password or some social network?

**Comment by bizley** [comment] 2016-12-07 22:03
I can confirm the following configuration works for `yii2-user` and `Podium` to run in cooperation:

    'bootstrap' => ['log', 'podium'],
    'components' => [
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
        'authManager' => [
            'class' => 'yii\rbac\DbManager',
        ],
    ],
    'modules' => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
        ],
        'podium' => [
            'class' => 'bizley\podium\Podium',
            'userComponent' => 'user',
            'rbacComponent' => 'authManager',
            'adminId' => 1,
            'userPasswordField' => 'password'
        ],
    ],

Setting `authManager` is required otherwise `yii2-user` forces to use it's built-in method `can` which ends with error while trying to check permissions for `Podium` (like when accessing `Administration` section).

While being logged in as `neo/neo` I've managed to change my `Podium` profile's email successfully confirming my current password (`neo`). Also I've changed the password in `yii2-user`, relogged and it was working as well.

Let me know if there are differences in your configuration so we can work this out.

**Comment by ekaterina-git** [comment] 2016-12-08 17:13
Thanks so much.
My config for authManager is \yii\rbac\PhpManager, maybe that's the thing... Can't I use it? Then I'll try to use DbManager later.

**Comment by bizley** [comment] 2016-12-08 17:28
I'm afraid Podium is not compatible with PhpManager. In case of large user pool storing RBAC data in files in not very effective.

I hope this is the only reason of the problem. I'm closing this issue for now, let me know if anything changes so we open it again.

**Closed as completed by bizley** 2016-12-08 17:28 UTC
Labels: question

**Comment by ekaterina-git** [comment] 2016-12-15 19:09
Thanks. It led me  to another bug, actually 😁 But it's not Podium related 😉
