### ISSUE TITLE
V. 0.2 Issues

### ISSUE THREAD

**Issue by ekaterina-git** [bizley/yii2-podium#30] opened 2016-09-03 21:28 UTC
Hi!
So I tried v. 0.2. I added to my app "dev-master" and updated the composer. Then I started the installation.
- First error: Undefined column: 7 ERROR:  column "blame" does not exist
  I've looked into log schema [here](https://github.com/bizley/yii2-podium/blob/master/src/maintenance/steps/install.php#L15) - and I noticed that column "blame" is not presented here :D You must've forgotten to rename index to 'user' [here](https://github.com/bizley/yii2-podium/blob/master/src/maintenance/steps/install.php#L47)
  Then installation went successfully.
- When I went on Podium main page I saw the error:

> PHP Fatal Error – yii\base\ErrorException Cannot access property bizley\podium\models\User::$_identity

So I changed [here](https://github.com/bizley/yii2-podium/blob/master/src/models/BaseUser.php#L86) all "static" to "self" and it worked.
- Then I came to "Members" page and got this:

> SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: `character varying
> LINE 1: ...."anonymous"=$1) AND ("user_id" IS NOT NULL) AND (`url` LIKE...
> ^

I came to inbox and saw this: 

> SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "."
> LINE 1: ...m1" LEFT JOIN "podium_message" "m2" ON `m1`.`replyto`...
> ^

I came to /podium/unread-posts and got similar problem :)

I fixed all quotes '`' I could find but I could've easily missed something
- The view file does not exist: ..../vendor/bizley/podium/src/views/forum/forum/edit.php
- I also fixed some Russian lines)

**Next things I didn't fix:**
- Also, if email is empty and I accidentally or on purpose set "use Gravatar", I constantly get an exception ('No email specified for Gravatar image Widget.') and can't even edit my account settings to uncheck this option
- If you post your answer AFTER previewing, you get an error "Post was not found".. Oh, no, it's worse actually) My answer was added but it was merged to my first one lol. So in fact my reply was added but I still got an error

**Comment by bizley** [comment] 2016-09-04 08:18
Thank you for all the work here.
0.2 is not stable yet so things are messy like you see.
I will merge all your changes but next time please create separated issues and PRs for each bug, it's easier to modify and comment. Also creating separate branches for each PR is good idea.

Could you expand some translations for plural constructs? Like `'{n, plural, =1{# anonymous user} other{# anonymous users}}' => 'Анонимных пользователей (за последние 15 минут): {n}',`
Read more about it in [the guide](http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#plural).

**Comment by ekaterina-git** [comment] 2016-09-04 09:30
> 0.2 is not stable yet so things are messy like you see.

That's ok, I understand it.

> I will merge all your changes but next time please create separated issues and PRs for each bug, it's easier to modify and comment. Also creating separate branches for each PR is good idea.

Oh, sure. Sorry, I'm new to PR and simply didn't know. I will!

> Could you expand some translations for plural constructs? Like '{n, plural, =1{# anonymous user} other{# anonymous users}}' => 'Анонимных пользователей (за последние 15 минут): {n}',
> Read more about it in the guide.

Yes, I could and I will. Sorry for my decision to remove plural constructs, I didn't see the guide before and thought it would be too hard to do it right.

**Comment by bizley** [comment] 2016-09-04 09:55
You can not use Gravatars without email anymore.

As for the post adding with/without preview - could you check if the problem is still there on the fresh dev-master version? I've made some changes and cannot reproduce this thing so maybe it's fixed now.

BTW Podium merges posts if previous one is made by the same author.

**Comment by ekaterina-git** [comment] 2016-09-04 18:52
> BTW Podium merges posts if previous one is made by the same author.

Yes, I got that.

> As for the post adding with/without preview - could you check if the problem is still there on the fresh dev-master version? I've made some changes and cannot reproduce this thing so maybe it's fixed now.

Unfortunately, it's still here. When I tried to delete the topic, I got

> PHP Warning – yii\base\ErrorException Illegal string offset 'thread' in .../vendor/bizley/podium/src/controllers/BaseForumActionsController.php at line 72

**Comment by bizley** [comment] 2016-09-04 18:53
Ok, and what about 

> If you post your answer AFTER previewing, you get an error "Post was not found".. Oh, no, it's worse actually) My answer was added but it was merged to my first one lol. So in fact my reply was added but I still got an error

**Comment by ekaterina-git** [comment] 2016-09-04 18:57
Yes, I deleted the thread and created a new one, but there's still this error. I'll try and see what causes it

**Comment by ekaterina-git** [comment] 2016-09-04 19:11
I now know. I use Postgres and it already caused so much trouble :( 

> SQLSTATE[42803]: Grouping error: 7 ERROR: column "podium_post.id" must appear in the GROUP BY clause or be used in an aggregate function
> LINE 1: ...m_post" WHERE ("thread_id"=$1) AND ("id" < $2) ORDER BY "id"
> ^
> The SQL being executed was: SELECT COUNT(*) FROM "podium_post" WHERE ("thread_id"=2) AND ("id" < 2) ORDER BY "id"

UPD Oh, it helped to remove 'orderBy' from [this chain](https://github.com/bizley/yii2-podium/blob/master/src/controllers/ForumController.php#L283).

**Comment by bizley** [comment] 2016-09-05 18:54
Thanks, this orderBy was totally not needed there. Let me know if something is still not ok.

**Comment by ekaterina-git** [comment] 2016-09-06 07:18
Everything looks fine at the moment, thanks for all your work, I really love Podium :heart_eyes: . I think we can close this issue?

**Comment by bizley** [comment] 2016-09-06 08:51
Cheers!

**Closed as completed by bizley** 2016-09-06 08:51 UTC
Labels: bug, enhancement
